keycloak:
  auth-server-url: http://192.168.123.157:8180/auth
  realm: expenses
  resource: expenses-app
  public-client: true
  principal-attribute: preferred_username
spring:
  application:
    name: expenses-processing-server
  datasource:
    url: jdbc:mysql://192.168.123.157:3306/expenses?useSSL=false
    username: spring
    password: expenses
    driverClassName: com.mysql.jdbc.Driver
  profiles: prod
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.123.204:8761/eureka/
  appInfo:
    replicate:
      interval: 3
    initial:
      replicate:
        time: 3
  instance:
    statusPageUrlPath: /info
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 3
    healthCheckUrlPath: /health
logging:
  file: myapplication.log