spring:
  application:
    name: expenses-processing-server
  datasource:
    url: jdbc:mysql://192.168.123.157:3306/processing?useSSL=false
    username: spring
    password: expenses
    driverClassName: com.mysql.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.123.204:8761/eureka/
  appInfo:
    replicate:
      interval: 3
    initial:
      replicate:
        time: 3
  instance:
    statusPageUrlPath: /info
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 3
    healthCheckUrlPath: /health
logging:
  file: myapplication.log
feign:
  client:
    config:
      service:
        booking: expenses-service
        project: account-service
        expenses: expenses-service