keycloak:
  auth-server-url: http://192.168.123.157:8180/auth
  realm: expenses
  resource: expenses-app
  public-client: true
  principal-attribute: preferred_username
spring:
  application:
    name: expenses-processing-server-ref
  client:
    serviceUrl:
      defaultZone: http://192.168.123.204:8761/eureka/
  appInfo:
    replicate:
      interval: 3
    initial:
      replicate:
        time: 3
  instance:
    statusPageUrlPath: /info
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 3
    healthCheckUrlPath: /health
log4j:
  logger:
    org:
      hibernate:
        type: INFO
server:
  port: 8090
