spring:
  rabbitmq:
    host: 192.168.123.176
    port: 5672
  application:
    name: expenses-processing-server
  cloud:
    stream:
      bindings:
        output:
          destination: orders-in
        input:
          destination: orders-out
          group: account
      rabbit:
        bindings:
          output:
            producer:
              exchangeType: direct
              routingKeyExpression: '"#"'
subscriber:
  routingKey: expenses.#
  queue: orderServiceQueue
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.123.204:8761/eureka/
  appInfo:
    replicate:
      interval: 3
    initial:
      replicate:
        time: 3
  instance:
    statusPageUrlPath: /actuator
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 3
    healthCheckUrlPath: /actuator/health
