keycloak:
  auth-server-url: http://192.168.123.157:8180/auth
  realm: expenses
  resource: expenses-app
  public-client: true
  principal-attribute: preferred_username
spring:
  application:
    name: expenses-processing-server
eureka:
  client:
    enabled: false
log4j:
  logger:
    org:
      hibernate:
        type: TRACE